import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/guest.css";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import { Toaster } from "@platter/ui/components/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="top-center" richColors />
        <div className="grid grid-rows-[auto,1fr,auto] min-h-screen">
          <main className="min-h-[calc(100vh-3.5rem)]">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
